DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE, 
    password TEXT NOT NULL
);

CREATE TABLE tasks(
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL, 
    done BOOLEAN DEFAULT false NOT NULL, 
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);